<!DOCTYPE html>
<html style="font-size: 16px;" lang="ru"><head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="">
    <meta name="description" content="">
    <title>Администрирование</title>
    <link rel="stylesheet" href="nicepage.css" media="screen">
<link rel="stylesheet" href="Администрирование.css" media="screen">
    <script class="u-script" type="text/javascript" src="jquery.js" defer=""></script>
    <script class="u-script" type="text/javascript" src="nicepage.js" defer=""></script>
    <meta name="generator" content="Nicepage 5.2.4, nicepage.com">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i">
    
    
    <script type="application/ld+json">{
		"@context": "http://schema.org",
		"@type": "Organization",
		"name": ""
}</script>
    <meta name="theme-color" content="#478ac9">
    <meta property="og:title" content="Администрирование">
    <meta property="og:type" content="website">

    <style type="text/css">
      .tabs { width: 100%; padding: 0px; margin: 0 auto; }
      .tabs>input { display: none; }
      .tabs>div {
          display: none;
          padding: 12px;
          border: 1px solid #C0C0C0;
          background: #FFFFFF;
      }
      .tabs>label {
          display: inline-block;
          padding: 7px;
          margin: 0 -5px -1px 0;
          text-align: center;
          color: #666666;
          border: 1px solid #C0C0C0;
          background: #E0E0E0;
          cursor: pointer;
      }
      .tabs>input:checked + label {
          color: #000000;
          border: 1px solid #C0C0C0;
          border-bottom: 1px solid #FFFFFF;
          background: #FFFFFF;
      }
      #tab_1:checked ~ #txt_1,
      #tab_2:checked ~ #txt_2,
      #tab_3:checked ~ #txt_3,
      #tab_4:checked ~ #txt_4 { display: block; }
      </style>
  </head>
  <body class="u-body u-xl-mode" data-lang="ru"><header class="u-clearfix u-gradient u-header u-sticky u-sticky-d624 u-header" id="sec-9805"><div class="u-clearfix u-sheet u-sheet-1">
        <p class="u-large-text u-text u-text-variant u-text-white u-text-1" data-animation-name="" data-animation-duration="0" data-animation-direction="">ЛУЧ</p>
        <nav class="u-menu u-menu-one-level u-offcanvas u-menu-1">
          <div class="menu-collapse u-custom-font u-font-arial" style="font-size: 1rem; letter-spacing: 2px; font-weight: 700;">
            <a class="u-button-style u-custom-color u-custom-left-right-menu-spacing u-custom-padding-bottom u-custom-text-active-color u-custom-text-hover-color u-custom-text-shadow u-custom-text-shadow-blur u-custom-text-shadow-color u-custom-text-shadow-transparency u-custom-text-shadow-x u-custom-text-shadow-y u-custom-top-bottom-menu-spacing u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="#">
              <svg class="u-svg-link" viewBox="0 0 24 24"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#menu-hamburger"></use></svg>
              <svg class="u-svg-content" version="1.1" id="menu-hamburger" viewBox="0 0 16 16" x="0px" y="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg"><g><rect y="1" width="16" height="2"></rect><rect y="7" width="16" height="2"></rect><rect y="13" width="16" height="2"></rect>
</g></svg>
            </a>
          </div>
          <div class="u-custom-menu u-nav-container">
            <ul class="u-custom-font u-font-arial u-nav u-spacing-0 u-unstyled u-nav-1"><li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-custom-color-4 u-text-hover-palette-2-dark-1" href="Главная.html" style="padding: 10px 20px;">Главная</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-custom-color-4 u-text-hover-palette-2-dark-1" href="Продукция.html" style="padding: 10px 20px;">Продукция</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-custom-color-4 u-text-hover-palette-2-dark-1" href="Контакты.html" style="padding: 10px 20px;">Контакты</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-custom-color-4 u-text-hover-palette-2-dark-1" href="Об-организации.html" style="padding: 10px 20px;">Об организации</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-custom-color-4 u-text-hover-palette-2-dark-1" href="Профиль.phtml" style="padding: 10px 20px;">Профиль</a>
</li></ul>
          </div>
          <div class="u-custom-menu u-nav-container-collapse">
            <div class="u-black u-container-style u-inner-container-layout u-opacity u-opacity-95 u-sidenav">
              <div class="u-inner-container-layout u-sidenav-overflow">
                <div class="u-menu-close"></div>
                <ul class="u-align-center u-nav u-popupmenu-items u-unstyled u-nav-2"><li class="u-nav-item"><a class="u-button-style u-nav-link" href="Главная.html">Главная</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="Продукция.html">Продукция</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="Контакты.html">Контакты</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="Об-организации.html">Об организации</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="Профиль.phtml">Профиль</a>
</li></ul>
              </div>
            </div>
            <div class="u-black u-menu-overlay u-opacity u-opacity-70"></div>
          </div>
        </nav>
      </div>
      <style class="u-sticky-style" data-style-id="d624">.u-sticky-fixed.u-sticky-d624:before, .u-body.u-sticky-fixed .u-sticky-d624:before {
borders: top right bottom left !important
}
.ac-container
  {
    margin-left: 100pt;
    margin-right: 100pt;
    padding-top: 10pt;
    padding-bottom: 10pt;
  }

  .ac-container label{
    font-family: 'BebasNeueRegular', 'Arial Narrow', Arial, sans-serif;
    padding: 5px 20px;
    position: relative;
    z-index: 20;
    display: block;
    height: 50px;
    cursor: pointer;
    color: #777;
    text-shadow: 1px 1px 1px rgba(255,255,255,0.8);
    line-height: 33px;
    font-size: 16px;
    background: -moz-linear-gradient(top, #ffffff 1%, #eaeaea 100%);
	background: -webkit-gradient(linear, left top, left bottom, color-stop(1%,#ffffff), color-stop(100%,#eaeaea));
	background: -webkit-linear-gradient(top, #ffffff 1%,#eaeaea 100%);
	background: -o-linear-gradient(top, #ffffff 1%,#eaeaea 100%);
	background: -ms-linear-gradient(top, #ffffff 1%,#eaeaea 100%);
	background: linear-gradient(top, #ffffff 1%,#eaeaea 100%);
	filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#ffffff', endColorstr='#eaeaea',GradientType=0 );
	box-shadow: 
		0px 0px 0px 1px rgba(155,155,155,0.3), 
		1px 0px 0px 0px rgba(255,255,255,0.9) inset, 
		0px 2px 2px rgba(0,0,0,0.1);
}

.ac-container label:hover{
    background: #fff;
}

.ac-container input:checked + label,
.ac-container input:checked + label:hover{
    background: #777;
    color: #ffffff;
    text-shadow: 0px 1px 1px rgba(255,255,255, 0.6);
    box-shadow: 
        0px 0px 0px 1px rgba(155,155,155,0.3), 
        0px 2px 2px rgba(0,0,0,0.1);
}

.ac-container label:hover:after,
.ac-container input:checked + label:hover:after{
    content: '';
    position: absolute;
    width: 24px;
    height: 24px;
    right: 13px;
    top: 7px;
    background: transparent url(http://netcribe.com/example/arrow_down.png) no-repeat center center;  
}

.ac-container input:checked + label:hover:after {
    background-image: url(http://netcribe.com/example/arrow_up.png);
}

.ac-container input{
    display: none;
}

.ac-container article{
    background: rgba(255, 255, 255, 0.5);
    margin-top: -1px;
    overflow: hidden;
    height: 0px;
    position: relative;
    z-index: 10;
    -webkit-transition: height 0.3s ease-in-out, box-shadow 0.6s linear;
	-moz-transition: height 0.3s ease-in-out, box-shadow 0.6s linear;
	-o-transition: height 0.3s ease-in-out, box-shadow 0.6s linear;
	-ms-transition: height 0.3s ease-in-out, box-shadow 0.6s linear;
	transition: height 0.3s ease-in-out, box-shadow 0.6s linear;
}
.ac-container input:checked ~ article{
     -webkit-transition: height 0.3s ease-in-out, box-shadow 0.6s linear;
	-moz-transition: height 0.3s ease-in-out, box-shadow 0.6s linear;
	-o-transition: height 0.3s ease-in-out, box-shadow 0.6s linear;
	-ms-transition: height 0.3s ease-in-out, box-shadow 0.6s linear;
	transition: height 0.3s ease-in-out, box-shadow 0.6s linear;
    box-shadow: 0px 0px 0px 1px rgba(155,155,155,0.3);
    height: 400px;
    overflow:scroll;
    
}

.ac-container article p{
    font-style: italic;
    color: #777;
    line-height: 23px;
    font-size: 14px;
    padding: 20px;
    text-shadow: 1px 1px 1px rgba(255,255,255,0.8);
}

.bblock{
        float: left; /*Задаем обтекание*/
     width: 320px; /*Фиксируем ширину блока*/
     margin-right: 10px;
    }
</style>
</header>

    <section class="u-clearfix u-section-1" id="sec-7ba7">

      <div class="tabs">
        <input type="radio" name="inset" value="" id="tab_1" checked >
        <label for="tab_1" style="margin-left: 100pt;">Управление продукцией</label>
    
        <input type="radio" name="inset" value="" id="tab_2">
        <label for="tab_2" style="margin-left: 50pt;">Управление заказами</label>
    
        <div id="txt_1">
          <div class="u-clearfix u-sheet u-sheet-1">
        
            <form action="addproduct.php" method="post" enctype="multipart/form-data">
              <div>Выберите тип</div>
              <select name="productType">
                <option>Бакалея</option>
                <option>Молочная продукция</option>
                <option>Сырая продукция</option>
                <option>Комбикорм</option>
                <option>С/Х животные и птица</option>
              </select>
              <div>Название продукции</div>
              <input name="productName"/>
              <div>Цена</div>
              <input name="productPrice"/>
              <div>Колличество</div>
              <input name="productCount"/>
              <div>Описание</div>
              <input name="productInfo"/>
              <div>Изображение</div>
    
              <input type="file" name="filename"/>
              <button type="submit">Добавить продукт</button>
            </form>
    
          </div>
        </div>
        <div id="txt_2">
          <section class="ac-container">

            <?php
              include 'orderlistadmin.php';
            ?>

          </section>
        </div>
      </div>
    </section>
  
</body></html>