<!DOCTYPE html>
<html style="font-size: 16px;" lang="ru"><head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    <meta name="keywords" content="Бакалея">
    <meta name="description" content="">
    <title>Бакалея</title>
    <link rel="stylesheet" href="nicepage.css" media="screen">
<link rel="stylesheet" href="Бакалея.css" media="screen">
    <script class="u-script" type="text/javascript" src="jquery.js" defer=""></script>
    <script class="u-script" type="text/javascript" src="nicepage.js" defer=""></script>
    <meta name="generator" content="Nicepage 5.2.4, nicepage.com">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i">
    
    
    
    <script type="application/ld+json">{
		"@context": "http://schema.org",
		"@type": "Organization",
		"name": ""
}</script>
    <meta name="theme-color" content="#478ac9">
    <meta property="og:title" content="Бакалея">
    <meta property="og:type" content="website">
  </head>
  <body class="u-body u-xl-mode" data-lang="ru"><header class="u-clearfix u-gradient u-header u-sticky u-sticky-d624 u-header" id="sec-9805"><div class="u-clearfix u-sheet u-sheet-1">
        <p class="u-large-text u-text u-text-variant u-text-white u-text-1" data-animation-name="" data-animation-duration="0" data-animation-direction="">ЛУЧ</p>
        <nav class="u-menu u-menu-one-level u-offcanvas u-menu-1">
          <div class="menu-collapse u-custom-font u-font-arial" style="font-size: 1rem; letter-spacing: 2px; font-weight: 700;">
            <a class="u-button-style u-custom-color u-custom-left-right-menu-spacing u-custom-padding-bottom u-custom-text-active-color u-custom-text-hover-color u-custom-text-shadow u-custom-text-shadow-blur u-custom-text-shadow-color u-custom-text-shadow-transparency u-custom-text-shadow-x u-custom-text-shadow-y u-custom-top-bottom-menu-spacing u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base" href="#">
              <svg class="u-svg-link" viewBox="0 0 24 24"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#menu-hamburger"></use></svg>
              <svg class="u-svg-content" version="1.1" id="menu-hamburger" viewBox="0 0 16 16" x="0px" y="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg"><g><rect y="1" width="16" height="2"></rect><rect y="7" width="16" height="2"></rect><rect y="13" width="16" height="2"></rect>
</g></svg>
            </a>
          </div>
          <div class="u-custom-menu u-nav-container">
            <ul class="u-custom-font u-font-arial u-nav u-spacing-0 u-unstyled u-nav-1"><li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-custom-color-4 u-text-hover-palette-2-dark-1" href="Главная.html" style="padding: 10px 20px;">Главная</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-custom-color-4 u-text-hover-palette-2-dark-1" href="Продукция.html" style="padding: 10px 20px;">Продукция</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-custom-color-4 u-text-hover-palette-2-dark-1" href="Контакты.html" style="padding: 10px 20px;">Контакты</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-custom-color-4 u-text-hover-palette-2-dark-1" href="Об-организации.html" style="padding: 10px 20px;">Об организации</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link u-text-active-custom-color-4 u-text-hover-palette-2-dark-1" href="Профиль.phtml" style="padding: 10px 20px;">Профиль</a>
</li></ul>
          </div>
          <div class="u-custom-menu u-nav-container-collapse">
            <div class="u-black u-container-style u-inner-container-layout u-opacity u-opacity-95 u-sidenav">
              <div class="u-inner-container-layout u-sidenav-overflow">
                <div class="u-menu-close"></div>
                <ul class="u-align-center u-nav u-popupmenu-items u-unstyled u-nav-2"><li class="u-nav-item"><a class="u-button-style u-nav-link" href="Главная.html">Главная</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="Продукция.html">Продукция</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="Контакты.html">Контакты</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="Об-организации.html">Об организации</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="Профиль.phtml">Профиль</a>
</li></ul>
              </div>
            </div>
            <div class="u-black u-menu-overlay u-opacity u-opacity-70"></div>
          </div>
        </nav>
      </div><style class="u-sticky-style" data-style-id="d624">.u-sticky-fixed.u-sticky-d624:before, .u-body.u-sticky-fixed .u-sticky-d624:before {
borders: top right bottom left !important
}</style></header>
    <section class="u-clearfix u-section-1" id="sec-781f">
      <div class="u-clearfix u-sheet u-valign-middle u-sheet-1">
        <h1 class="u-text u-text-default u-text-1">Комбикорм<br>
        </h1>
      </div>
    </section>

    <?php

      include 'connect.php';

      //echo "Контекст установлен!<br>";

      $result= $db->query('SELECT product_name, product_price, product_info, product_type, product_photo, product_count FROM Products WHERE product_type = "Комбикорм"');

      foreach($result as $row) 
      {
          echo '
          <section class="u-clearfix u-section-2" id="sec-6021">
            <div class="u-clearfix u-sheet u-sheet-1">
              <div class="u-border-3 u-border-custom-color-4 u-container-style u-expanded-width u-group u-group-1">
                <div class="u-container-layout u-container-layout-1">
                  <img class="u-image u-image-1" data-image-width="1024" data-image-height="692" src="'.$row['product_photo'].'">
                  <h3 class="u-text u-text-default u-text-1">'.$row['product_name'].'</h3>
                  <p class="u-align-center u-text u-text-2">'.$row['product_price'].' р.<br>
                  </p>
                  <p class="u-text u-text-3">'.$row['product_info'].'<br>
                  </p>';

                  $count = $row['product_count'];
                  if($count >= 1)
                  {
                      echo '
                      <form action="addbasket.php" method="post">
                        <input type="hidden" name="productName" value="'.$row['product_name'].'"/>
                        <input type="hidden" name="productPrice" value="'.$row['product_price'].'"/>
                        <input type="hidden" name="productType" value="'.$row['product_type'].'"/>
                        <button type="submit" class="u-active-custom-color-10 u-btn u-button-style u-custom-color-4 u-hover-custom-color-9 u-hover-feature u-btn-1">В корзину</button>
                      </form>
                      ';
                  }
                  else
                  {
                    echo '
                    <form disabled="disabled">
                      <input type="hidden" name="productName" value="'.$row['product_name'].'"/>
                      <input type="hidden" name="productPrice" value="'.$row['product_price'].'"/>
                      <input type="hidden" name="productType" value="'.$row['product_type'].'"/>
                      <button disabled="disabled" class="u-active-custom-color-10 u-btn u-button-style u-custom-color-4 u-hover-custom-color-9 u-hover-feature u-btn-1">Нет в наличии</button>
                    </form>
                    ';
                  }
                  
                  echo '
                </div>
              </div>
            </div>
          </section>';
      }
    ?>
    
    <footer class="u-align-center u-clearfix u-footer u-grey-80 u-footer" id="sec-3b0d" 
    style="flex: 0 0 auto;">
      <div class="u-clearfix u-sheet u-valign-middle u-sheet-1">
        <p class="u-align-left u-text u-text-default u-text-1" >ООО «Луч».

        Адрес: 422952,
        Республика Татарстан, Чистопольский р-н, п. Луч. Телефон:
        +78434247322.</p>
      </div>
    </footer>
  
</body></html>